In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

In [2]:
dataset=pd.read_csv("Lead_Scoring.csv")

In [3]:
dataset

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [4]:
dataset.describe()

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
count,9240.000000,9240.000000,9103.000000,9240.000000,9103.000000,5022.000000,5022.000000
mean,617188.435606,0.385390,3.445238,487.698268,2.362820,14.306252,16.344883
std,23405.995698,0.486714,4.854853,548.021466,2.161418,1.386694,1.811395
min,579533.000000,0.000000,0.000000,0.000000,0.000000,7.000000,11.000000
25%,596484.500000,0.000000,1.000000,12.000000,1.000000,14.000000,15.000000
50%,615479.000000,0.000000,3.000000,248.000000,2.000000,14.000000,16.000000
75%,637387.250000,1.000000,5.000000,936.000000,3.000000,15.000000,18.000000
max,660737.000000,1.000000,251.000000,2272.000000,55.000000,18.000000,20.000000

In [5]:
dataset.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   1438
How did you hear about X Education               2207
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Lead Quality                                     4767
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                     2709
City                                             1420
Asymmetrique Activity Index                      4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [6]:
dataset[dataset['Lead Source'].isnull()]

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
836,b2dfb7a5-814d-465b-816e-63d6b3a863ca,651660,Lead Add Form,NaN,Yes,No,1,NaN,1378,NaN,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,Modified
1569,1c87e9fd-c675-468e-9653-2cc968f077f2,643899,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
1746,215e9984-818a-42ff-ba1c-667ce73199a5,642394,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
2020,06f5b430-a45a-4de2-9aca-e13ee0a43589,640115,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
2025,e7524e35-923e-4c9f-800d-b18e1a6c5e3b,640081,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
2152,e54f76cc-2436-451c-8a29-fcd32ed7bed4,639134,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
2346,c309cc6d-204f-4ac0-a766-7d326bd01218,637125,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
2544,175611de-436d-11e6-b61b-22000aa8e760,635028,Lead Import,NaN,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,15.0,No,No,Email Opened
2601,bbe44370-ea5a-4e46-99d9-d32cfbd32199,634618,Quick Add Form,NaN,Yes,No,1,NaN,2217,NaN,...,No,Select,Other Metro Cities,02.Medium,02.Medium,14.0,13.0,No,No,Modified
2676,bcfdd00e-99d2-4be1-b09b-a6260a63dade,633945,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Potential Lead,Other Cities of Maharashtra,NaN,NaN,NaN,NaN,No,No,SMS Sent
3028,6238e5d6-2708-4d78-8180-82fd603c8a22,630801,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
3266,1081fb9a-3309-46b6-a890-74de644e05c8,628685,Landing Page Submission,NaN,No,No,1,2.0,9,2.0,...,No,Select,Mumbai,NaN,NaN,NaN,NaN,No,No,SMS Sent
3268,4a959213-0cef-4b5f-bab0-9198557b5d8f,628666,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
3928,829524dc-e9c8-4f6d-8947-591e1c1746b0,622403,Lead Add Form,NaN,Yes,No,0,NaN,44,NaN,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified
3945,f7aa46f0-2fe2-459a-8235-66e132910778,622280,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
4406,348bc75a-dbb6-4605-8d4a-fb02da9d48e2,617520,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
4409,19fd3dc0-dd17-4490-8d10-364de953b7e7,617495,Lead Add Form,NaN,No,No,0,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Email Opened
4605,393a4d46-8f73-43a4-966a-43d22773ba68,615643,Lead Add Form,NaN,Yes,No,0,NaN,156,NaN,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
4653,abd3afd7-7f13-4111-9710-d84fe67c8888,615069,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
4804,53ef2d0f-c083-4629-a434-e0693f5fdf69,613917,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Email Opened
4831,7e508a13-6f61-4e5d-834d-52573fb85b33,613660,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified
4843,99e07a6e-5071-4211-bef3-f3b322effe6a,613583,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
5253,12a7df19-b6dd-4e53-abd7-3d869069189a,609475,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
5621,1f442c0a-4c91-4ba7-858a-589e78ade2bb,606860,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Potential Lead,Thane & Outskirts,NaN,NaN,NaN,NaN,No,No,SMS Sent
5840,08b0957c-8296-4e8e-bc4a-1c688f1a1f7e,605099,Lead Add Form,NaN,No,No,1,NaN,506,NaN,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified
5960,7ec55e1d-0868-4812-99ed-474f03ed35e8,604134,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
6124,58690710-0a0b-4209-a64d-46317163c4b8,602759,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
7302,5e748f60-2b1c-4793-a143-6b097df3aa88,593400,Lead Add Form,NaN,Yes,No,0,NaN,926,NaN,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
7306,1f691d7c-ccdb-467c-9302-30e8af12688a,593374,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
7525,32fc4033-a135-422e-829f-603355119cba,591848,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Potential Lead,Mumbai,02.Medium,02.Medium,15.0,16.0,No,No,Unsubscribed
7847,66099c96-232e-4156-97c3-9040650798db,589591,Lead Add Form,NaN,No,No,0,NaN,289,NaN,...,No,Select,Select,02.Medium,02.Medium,13.0,16.0,No,No,Modified
8092,ae60c38c-6869-44a9-8ba7-43a77bc1e845,587995,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,Email Opened
8118,80f5897b-9092-40f4-86e3-029d988ba27b,587880,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Potential Lead,Select,02.Medium,01.High,14.0,17.0,No,No,SMS Sent
8276,3e03ad49-784e-430a-908d-abb7b4e9dfc7,586678,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
8490,95832f2b-d5b1-47c7-8be4-4523a358ae25,584932,Lead Add Form,NaN,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,13.0,16.0,No,No,SMS Sent
9160,96467c35-9981-463e-be86-0028408d8e53,580221,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Potential Lead,Select,02.Medium,01.High,14.0,17.0,No,No,Unsubscribed

In [7]:
dataset = dataset.dropna(subset=['Converted'])

In [8]:
dataset = dataset.dropna(subset=['Lead Source'])

In [9]:
dataset['Country'] = dataset['Country'].fillna('NA')
dataset['Specialization'] = dataset['Specialization'].fillna('NA')
dataset['What is your current occupation'] = dataset['What is your current occupation'].fillna('NA')
dataset['Lead Quality'] = dataset['Lead Quality'].fillna('NA')
dataset['Lead Profile'] = dataset['Lead Profile'].fillna('NA')
dataset['City'] = dataset['City'].fillna('NA')
dataset['Tags'] = dataset['Tags'].fillna('NA')

In [10]:
dataset.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                         0
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       130
Total Time Spent on Website                         0
Page Views Per Visit                              130
Last Activity                                     101
Country                                             0
Specialization                                      0
How did you hear about X Education               2207
What is your current occupation                     0
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                                0
Lead Quality                                        0
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                        0
City                                                0
Asymmetrique Activity Index                      4201
Asymmetrique Profile Index                       4201
Asymmetrique Activity Score                      4201
Asymmetrique Profile Score                       4201
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9204 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Prospect ID                                    9204 non-null   object
 1   Lead Number                                    9204 non-null   int64
 2   Lead Origin                                    9204 non-null   object
 3   Lead Source                                    9204 non-null   object
 4   Do Not Email                                   9204 non-null   object
 5   Do Not Call                                    9204 non-null   object
 6   Converted                                      9204 non-null   int64
 7   TotalVisits                                    9074 non-null   float64
 8   Total Time Spent on Website                    9204 non-null   int64
 9   Page Views Per Visit                           9074 non-null   float64
 10  Last Activity                                  9103 non-null   object
 11  Country                                        9204 non-null   object
 12  Specialization                                 9204 non-null   object
 13  How did you hear about X Education             6997 non-null   object
 14  What is your current occupation                9204 non-null   object
 15  What matters most to you in choosing a course  6495 non-null   object
 16  Search                                         9204 non-null   object
 17  Magazine                                       9204 non-null   object
 18  Newspaper Article                              9204 non-null   object
 19  X Education Forums                             9204 non-null   object
 20  Newspaper                                      9204 non-null   object
 21  Digital Advertisement                          9204 non-null   object
 22  Through Recommendations                        9204 non-null   object
 23  Receive More Updates About Our Courses         9204 non-null   object
 24  Tags                                           9204 non-null   object
 25  Lead Quality                                   9204 non-null   object
 26  Update me on Supply Chain Content              9204 non-null   object
 27  Get updates on DM Content                      9204 non-null   object
 28  Lead Profile                                   9204 non-null   object
 29  City                                           9204 non-null   object
 30  Asymmetrique Activity Index                    5003 non-null   object
 31  Asymmetrique Profile Index                     5003 non-null   object
 32  Asymmetrique Activity Score                    5003 non-null   float64
 33  Asymmetrique Profile Score                     5003 non-null   float64
 34  I agree to pay the amount through cheque       9204 non-null   object
 35  A free copy of Mastering The Interview         9204 non-null   object
 36  Last Notable Activity                          9204 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.7+ MB

In [12]:
dataset.columns

Index(['Prospect ID', 'Lead Number', 'Lead Origin', 'Lead Source',
       'Do Not Email', 'Do Not Call', 'Converted', 'TotalVisits',
       'Total Time Spent on Website', 'Page Views Per Visit', 'Last Activity',
       'Country', 'Specialization', 'How did you hear about X Education',
       'What is your current occupation',
       'What matters most to you in choosing a course', 'Search', 'Magazine',
       'Newspaper Article', 'X Education Forums', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Courses', 'Tags', 'Lead Quality',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'Lead Profile', 'City', 'Asymmetrique Activity Index',
       'Asymmetrique Profile Index', 'Asymmetrique Activity Score',
       'Asymmetrique Profile Score',
       'I agree to pay the amount through cheque',
       'A free copy of Mastering The Interview', 'Last Notable Activity'],
      dtype='object')

In [13]:
quan=[]
qual=[]
for columnName in dataset.columns:
    print(columnName)
    if(dataset[columnName].dtype=='O'):
        print("qual")
        qual.append(columnName)
    else:
        print("quan")
        quan.append(columnName)

Prospect ID
qual
Lead Number
quan
Lead Origin
qual
Lead Source
qual
Do Not Email
qual
Do Not Call
qual
Converted
quan
TotalVisits
quan
Total Time Spent on Website
quan
Page Views Per Visit
quan
Last Activity
qual
Country
qual
Specialization
qual
How did you hear about X Education
qual
What is your current occupation
qual
What matters most to you in choosing a course
qual
Search
qual
Magazine
qual
Newspaper Article
qual
X Education Forums
qual
Newspaper
qual
Digital Advertisement
qual
Through Recommendations
qual
Receive More Updates About Our Courses
qual
Tags
qual
Lead Quality
qual
Update me on Supply Chain Content
qual
Get updates on DM Content
qual
Lead Profile
qual
City
qual
Asymmetrique Activity Index
qual
Asymmetrique Profile Index
qual
Asymmetrique Activity Score
quan
Asymmetrique Profile Score
quan
I agree to pay the amount through cheque
qual
A free copy of Mastering The Interview
qual
Last Notable Activity
qual

In [14]:
def quanQual(dataset):
    quan = []
    qual = []

    for columnName in dataset.columns:
        print(columnName)

        if dataset[columnName].dtype == 'O':
            print("qual")
            qual.append(columnName)
        else:
            print("quan")
            quan.append(columnName)

    return quan, qual

In [15]:
quanQual(dataset)

Prospect ID
qual
Lead Number
quan
Lead Origin
qual
Lead Source
qual
Do Not Email
qual
Do Not Call
qual
Converted
quan
TotalVisits
quan
Total Time Spent on Website
quan
Page Views Per Visit
quan
Last Activity
qual
Country
qual
Specialization
qual
How did you hear about X Education
qual
What is your current occupation
qual
What matters most to you in choosing a course
qual
Search
qual
Magazine
qual
Newspaper Article
qual
X Education Forums
qual
Newspaper
qual
Digital Advertisement
qual
Through Recommendations
qual
Receive More Updates About Our Courses
qual
Tags
qual
Lead Quality
qual
Update me on Supply Chain Content
qual
Get updates on DM Content
qual
Lead Profile
qual
City
qual
Asymmetrique Activity Index
qual
Asymmetrique Profile Index
qual
Asymmetrique Activity Score
quan
Asymmetrique Profile Score
quan
I agree to pay the amount through cheque
qual
A free copy of Mastering The Interview
qual
Last Notable Activity
qual

(['Lead Number',
  'Converted',
  'TotalVisits',
  'Total Time Spent on Website',
  'Page Views Per Visit',
  'Asymmetrique Activity Score',
  'Asymmetrique Profile Score'],
 ['Prospect ID',
  'Lead Origin',
  'Lead Source',
  'Do Not Email',
  'Do Not Call',
  'Last Activity',
  'Country',
  'Specialization',
  'How did you hear about X Education',
  'What is your current occupation',
  'What matters most to you in choosing a course',
  'Search',
  'Magazine',
  'Newspaper Article',
  'X Education Forums',
  'Newspaper',
  'Digital Advertisement',
  'Through Recommendations',
  'Receive More Updates About Our Courses',
  'Tags',
  'Lead Quality',
  'Update me on Supply Chain Content',
  'Get updates on DM Content',
  'Lead Profile',
  'City',
  'Asymmetrique Activity Index',
  'Asymmetrique Profile Index',
  'I agree to pay the amount through cheque',
  'A free copy of Mastering The Interview',
  'Last Notable Activity'])

In [16]:
quan,qual=quanQual(dataset)

Prospect ID
qual
Lead Number
quan
Lead Origin
qual
Lead Source
qual
Do Not Email
qual
Do Not Call
qual
Converted
quan
TotalVisits
quan
Total Time Spent on Website
quan
Page Views Per Visit
quan
Last Activity
qual
Country
qual
Specialization
qual
How did you hear about X Education
qual
What is your current occupation
qual
What matters most to you in choosing a course
qual
Search
qual
Magazine
qual
Newspaper Article
qual
X Education Forums
qual
Newspaper
qual
Digital Advertisement
qual
Through Recommendations
qual
Receive More Updates About Our Courses
qual
Tags
qual
Lead Quality
qual
Update me on Supply Chain Content
qual
Get updates on DM Content
qual
Lead Profile
qual
City
qual
Asymmetrique Activity Index
qual
Asymmetrique Profile Index
qual
Asymmetrique Activity Score
quan
Asymmetrique Profile Score
quan
I agree to pay the amount through cheque
qual
A free copy of Mastering The Interview
qual
Last Notable Activity
qual

In [17]:
quan

['Lead Number',
 'Converted',
 'TotalVisits',
 'Total Time Spent on Website',
 'Page Views Per Visit',
 'Asymmetrique Activity Score',
 'Asymmetrique Profile Score']

In [18]:
qual

['Prospect ID',
 'Lead Origin',
 'Lead Source',
 'Do Not Email',
 'Do Not Call',
 'Last Activity',
 'Country',
 'Specialization',
 'How did you hear about X Education',
 'What is your current occupation',
 'What matters most to you in choosing a course',
 'Search',
 'Magazine',
 'Newspaper Article',
 'X Education Forums',
 'Newspaper',
 'Digital Advertisement',
 'Through Recommendations',
 'Receive More Updates About Our Courses',
 'Tags',
 'Lead Quality',
 'Update me on Supply Chain Content',
 'Get updates on DM Content',
 'Lead Profile',
 'City',
 'Asymmetrique Activity Index',
 'Asymmetrique Profile Index',
 'I agree to pay the amount through cheque',
 'A free copy of Mastering The Interview',
 'Last Notable Activity']

In [28]:
dataset = dataset.drop(['Prospect ID', 'Lead Number'], axis=1)

In [29]:
dataset

,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,API,Olark Chat,No,No,0,0.0,0,0.00,Page Visited on Website,NA,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,India,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,India,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,India,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,India,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,Saudi Arabia,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,India,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,SMS Sent,India,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,Landing Page Submission,Google,No,No,1,3.0,499,3.00,SMS Sent,India,...,No,NA,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,Bangladesh,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [30]:
dataset.shape

(9204, 35)

In [31]:
dependent = dataset['Converted']

In [32]:
independent = dataset.drop('Converted', axis=1)

In [33]:
print("Independent shape:", independent.shape)
print("Dependent shape:", dependent.shape)

Independent shape: (9204, 34)
Dependent shape: (9204,)

In [34]:
quan, qual = quanQual(independent)

print("Quantitative:")
print(quan)

print("\nQualitative:")
print(qual)

Lead Origin
qual
Lead Source
qual
Do Not Email
qual
Do Not Call
qual
TotalVisits
quan
Total Time Spent on Website
quan
Page Views Per Visit
quan
Last Activity
qual
Country
qual
Specialization
qual
How did you hear about X Education
qual
What is your current occupation
qual
What matters most to you in choosing a course
qual
Search
qual
Magazine
qual
Newspaper Article
qual
X Education Forums
qual
Newspaper
qual
Digital Advertisement
qual
Through Recommendations
qual
Receive More Updates About Our Courses
qual
Tags
qual
Lead Quality
qual
Update me on Supply Chain Content
qual
Get updates on DM Content
qual
Lead Profile
qual
City
qual
Asymmetrique Activity Index
qual
Asymmetrique Profile Index
qual
Asymmetrique Activity Score
quan
Asymmetrique Profile Score
quan
I agree to pay the amount through cheque
qual
A free copy of Mastering The Interview
qual
Last Notable Activity
qual
Quantitative:
['TotalVisits', 'Total Time Spent on Website', 'Page Views Per Visit', 'Asymmetrique Activity Score', 'Asymmetrique Profile Score']

Qualitative:
['Lead Origin', 'Lead Source', 'Do Not Email', 'Do Not Call', 'Last Activity', 'Country', 'Specialization', 'How did you hear about X Education', 'What is your current occupation', 'What matters most to you in choosing a course', 'Search', 'Magazine', 'Newspaper Article', 'X Education Forums', 'Newspaper', 'Digital Advertisement', 'Through Recommendations', 'Receive More Updates About Our Courses', 'Tags', 'Lead Quality', 'Update me on Supply Chain Content', 'Get updates on DM Content', 'Lead Profile', 'City', 'Asymmetrique Activity Index', 'Asymmetrique Profile Index', 'I agree to pay the amount through cheque', 'A free copy of Mastering The Interview', 'Last Notable Activity']

In [35]:
independent = pd.get_dummies(
    independent,
    columns=qual,
    drop_first=True,
    dtype=int
)

In [36]:
independent

,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Source_Direct Traffic,Lead Source_Facebook,...,Last Notable Activity_Form Submitted on Website,Last Notable Activity_Had a Phone Conversation,Last Notable Activity_Modified,Last Notable Activity_Olark Chat Conversation,Last Notable Activity_Page Visited on Website,Last Notable Activity_Resubscribed to emails,Last Notable Activity_SMS Sent,Last Notable Activity_Unreachable,Last Notable Activity_Unsubscribed,Last Notable Activity_View in browser link Clicked
0,0.0,0,0.00,15.0,15.0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,5.0,674,2.50,15.0,15.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2.0,1532,2.00,14.0,20.0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1.0,305,1.00,13.0,17.0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
4,2.0,1428,1.00,15.0,18.0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,8.0,1845,2.67,15.0,17.0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9236,2.0,238,2.00,14.0,19.0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
9237,2.0,199,2.00,13.0,20.0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
9238,3.0,499,3.00,15.0,16.0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9239,6.0,1279,3.00,15.0,18.0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0

In [37]:
independent.isnull().sum().sum()

8662

In [38]:
dependent.isnull().sum()

0

In [39]:
independent.isnull().sum().sort_values(ascending=False)

Asymmetrique Activity Score                           4201
Asymmetrique Profile Score                            4201
TotalVisits                                            130
Page Views Per Visit                                   130
Tags_Interested  in full time MBA                        0
                                                      ...
Country_Oman                                             0
Country_Philippines                                      0
Country_Qatar                                            0
Country_Russia                                           0
Last Notable Activity_View in browser link Clicked       0
Length: 190, dtype: int64

In [40]:
num_cols = [
    'Asymmetrique Activity Score',
    'Asymmetrique Profile Score',
    'TotalVisits',
    'Page Views Per Visit'
]

for col in num_cols:
    independent[col] = independent[col].fillna(independent[col].median())

In [41]:
independent.isnull().sum().sort_values(ascending=False).head()

TotalVisits                                   0
Tags_In confusion whether part time or DLP    0
Newspaper Article_Yes                         0
X Education Forums_Yes                        0
Newspaper_Yes                                 0
dtype: int64

In [42]:
independent.isnull().sum().sum()

0