In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [47]:
def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=f_regression, k=n)
        fit1= test.fit(indep_X,dep_Y)
        # summarize scores       
        selectk_features = fit1.transform(indep_X)
        return selectk_features

In [48]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

In [49]:
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2

In [50]:
def Linear(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [51]:
def svm_linear(X_train,y_train,X_test):                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [52]:
def svm_NL(X_train,y_train,X_test):                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [53]:
def Decision(X_train,y_train,X_test):        
        # Fitting K-NN to the Training setC
        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [56]:
def selectk_regression(acclin,accsvml,accsvmnl,accdes): 
    dataframe=pd.DataFrame(index=['f_regression'],columns=['Linear','SVMl','SVMnl','Decision'])

    for number,idex in enumerate(dataframe.index):
        
        dataframe['Linear'][idex]=acclin[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        
    return dataframe

In [57]:
dataset1=pd.read_csv("Lead_Scoring_Preprocessing.csv",index_col=None)

In [58]:
df2=dataset1.copy()

In [59]:
df2 = pd.get_dummies(df2, drop_first=True,dtype=int)

In [60]:
indep_X=df2.drop('Estimated_Lead_Value', axis=1)
dep_Y=df2['Estimated_Lead_Value']

In [61]:
df2

,Lead_ID,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,...,Lead_Source_Facebook,Lead_Source_Google,Lead_Source_LinkedIn,Lead_Source_Referral,Lead_Source_Website,Industry_Finance,Industry_Healthcare,Industry_IT,Industry_Manufacturing,Industry_Retail
0,10001,4.0,1408.0,4.93,11.0,6,12,20.66,43,65285.0,...,0,0,0,0,1,0,0,1,0,0
1,10002,3.0,514.0,6.95,15.0,9,15,78.89,41,91555.0,...,0,0,0,1,0,0,0,0,1,0
2,10003,13.0,791.0,13.09,13.0,2,0,32.17,33,142713.0,...,0,0,1,0,0,1,0,0,0,0
3,10004,23.0,73.0,8.57,15.0,4,5,92.98,57,57471.0,...,0,0,0,1,0,0,1,0,0,0
4,10005,9.0,600.0,1.13,7.0,6,12,91.42,46,73671.0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785,11796,13.0,1159.0,9.11,14.0,7,10,80.53,39,86829.0,...,0,0,0,0,1,0,0,0,0,0
1786,11797,30.0,1428.0,13.33,0.0,6,7,44.76,49,30037.0,...,0,0,0,0,0,0,0,0,0,1
1787,11798,7.0,727.0,14.82,15.0,1,6,93.77,30,85526.0,...,0,1,0,0,0,0,0,0,1,0
1788,11799,26.0,1152.0,13.04,4.0,0,7,72.54,32,86829.0,...,1,0,0,0,0,0,1,0,0,0
1789,11800,20.0,623.0,3.67,2.0,6,11,54.91,50,39693.0,...,0,0,0,0,0,1,0,0,0,0

In [74]:
kbest=selectkbest(indep_X,dep_Y,12)     

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]

In [75]:
kbest

array([[4.000e+00, 1.408e+03, 4.930e+00, ..., 9.300e+01, 0.000e+00,
        1.000e+00],
       [3.000e+00, 5.140e+02, 6.950e+00, ..., 6.900e+01, 0.000e+00,
        0.000e+00],
       [1.300e+01, 7.910e+02, 1.309e+01, ..., 1.170e+02, 0.000e+00,
        0.000e+00],
       ...,
       [7.000e+00, 7.270e+02, 1.482e+01, ..., 7.300e+01, 0.000e+00,
        0.000e+00],
       [2.600e+01, 1.152e+03, 1.304e+01, ..., 6.000e+00, 1.000e+00,
        0.000e+00],
       [2.000e+01, 6.230e+02, 3.670e+00, ..., 1.500e+01, 0.000e+00,
        0.000e+00]])

In [76]:
X_train, X_test, y_train, y_test = split_scalar(kbest, dep_Y)

r2_lin = Linear(X_train, y_train, X_test)
acclin.append(r2_lin)

r2_sl = svm_linear(X_train, y_train, X_test)
accsvml.append(r2_sl)

r2_NL = svm_NL(X_train, y_train, X_test)
accsvmnl.append(r2_NL)

r2_d = Decision(X_train, y_train, X_test)
accdes.append(r2_d)

In [77]:
result=selectk_regression(acclin,accsvml,accsvmnl,accdes)

In [78]:
import warnings
warnings.filterwarnings("ignore")

In [79]:
result

                Linear      SVMl     SVMnl  Decision
f_regression  0.947518  0.089274  0.000968  0.661773

In [88]:
from sklearn.linear_model import LinearRegression
final_model = LinearRegression()
final_model.fit(X_train, y_train)

LinearRegression()

In [89]:
from sklearn.metrics import r2_score

y_pred = final_model.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("Final Model R2 Score:", r2)

Final Model R2 Score: 0.9475184739235023

In [90]:
import pickle
filename= "finalized_model_linear.sav"

In [84]:
pickle.dump(final_model, open("Lead_Scoring_Linear_Regression.pkl", "wb"))